apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app-stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-app
      version: stable
  template:
    metadata:
      labels:
        app: canary-app
        version: stable
    spec:
      containers:
        - name: canary-app
          image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/canary-app:v1
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-app
      version: preview
  template:
    metadata:
      labels:
        app: canary-app
        version: preview
    spec:
      containers:
        - name: canary-app
          image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/canary-app:v2
          ports:
            - containerPort: 8080
