apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-app
      version: blue
  template:
    metadata:
      labels:
        app: blue-green-app
        version: blue
    spec:
      containers:
        - name: app
          image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/blue-green-app:blue
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: blue-green-app
      version: green
  template:
    metadata:
      labels:
        app: blue-green-app
        version: green
    spec:
      containers:
        - name: app
          image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/blue-green-app:green
          ports:
            - containerPort: 8080